name: build
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/build.yml'
      - 'tsconfig.json'
      - 'yarn.lock'
jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
