name: publish
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Switch to main branch from tag
        run: |
          git fetch
          git switch main
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: yarn
      - name: Print environment info
        run: |
          echo "Node: $(node -v)"
          echo "Yarn: $(yarn -v)"
      - name: Install dependencies
        run: yarn
      - name: Set version number
        run: yarn version "${{ github.event.release.tag_name }}"
      - name: Publish to npmjs.org
        run: yarn npm publish --access public
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          YARN_NPM_REGISTRY_SERVER: 'https://registry.npmjs.org'
      - name: Push to git
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git add package.json .yarn/versions/*
          MESSAGE="Bump version to ${{ github.event.release.tag_name }}"
          git commit -m $MESSAGE
          git tag -f -a ${{ github.event.release.tag_name }} -m $MESSAGE
          git push
          git push origin -f ${{ github.event.release.tag_name }}
