name: update-symbols
on:
  workflow_dispatch:
jobs:
  update-symbols:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Run update script
        run: yarn update-symbols
      - name: Determine if any changes were made
        id: has-changes
        shell: bash
        run: |
          RESULT=$(git status --porcelain --untracked-files=no)
          if [[ $RESULT == *"src/types-common.ts"* ]]; then
            echo "::set-output name=result::true"
          fi
      - name: Push to git
        if: contains(steps.has-changes.outputs.result, 'true')
        run: |
          git add src/types-common.ts
          git commit -m "Update symbols from exchange"
          git push